# Generated by Django 5.0.6 on 2024-07-05 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='uploaded_images/')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keywords', models.TextField()),
                ('size', models.PositiveIntegerField()),
                ('resolution', models.CharField(max_length=50)),
                ('file_format', models.CharField(max_length=20)),
                ('dpi', models.PositiveIntegerField()),
                ('uploaded_datetime', models.DateTimeField()),
                ('sold_multiple_counter', models.PositiveIntegerField(default=0)),
                ('liked_by_counter', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user_registration')),
            ],
            options={
                'db_table': 'uploaded_images',
            },
        ),
    ]
