# Generated by Django 5.0.6 on 2024-07-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_images',
            old_name='user',
            new_name='user_id',
        ),
    ]
