# Generated by Django 5.0.6 on 2024-07-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0003_rename_user_id_upload_images_user'),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_images',
            name='liked_by_counter',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='upload_images',
            name='sold_multiple_counter',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='liked_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_dashboard.upload_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user_registration')),
            ],
            options={
                'db_table': 'liked_images',
                'unique_together': {('user', 'image')},
            },
        ),
    ]
