# Generated by Django 5.0.6 on 2024-07-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0004_alter_upload_images_liked_by_counter_and_more'),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchased_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('terms_accepted', models.BooleanField()),
                ('purchase_from', models.CharField(max_length=50)),
                ('purchase_date', models.DateTimeField()),
                ('payment_success', models.BooleanField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_dashboard.upload_images')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user_registration')),
            ],
            options={
                'db_table': 'purchased_items',
            },
        ),
    ]
