# Generated by Django 5.0.6 on 2024-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0005_purchased_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_items',
            name='terms_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
