# Generated by Django 5.0.6 on 2024-07-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0007_contact_us'),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='support_ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='ticket_images/')),
                ('submit_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('solved', 'Solved')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user_registration')),
            ],
            options={
                'db_table': 'support_ticket',
            },
        ),
    ]
