# Generated by Django 5.0.6 on 2024-07-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0011_alter_liked_images_liked_datetime'),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField()),
                ('message', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='discussion_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_registration.user_registration')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_dashboard.support_ticket')),
            ],
            options={
                'db_table': 'ticket_discussion',
            },
        ),
    ]
