# Generated by Django 5.0.6 on 2024-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0014_earning_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning_centre',
            name='withdrawn_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
