# Generated by Django 5.0.6 on 2024-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0015_earning_centre_withdrawn_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earning_centre',
            name='remaining_amount',
        ),
    ]
