# Generated by Django 5.0.6 on 2024-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0016_remove_earning_centre_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning_centre',
            name='total_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='earning_centre',
            name='withdrawn_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
