# Generated by Django 5.0.6 on 2024-07-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0017_alter_earning_centre_total_earned_and_more'),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_items',
            name='purchase_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_from', to='user_registration.user_registration'),
        ),
        migrations.AlterField(
            model_name='purchased_items',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by', to='user_registration.user_registration'),
        ),
    ]
