# Generated by Django 5.0.6 on 2024-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0019_image_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_images',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
