# Generated by Django 5.0.6 on 2024-07-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0020_upload_images_is_active'),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('profession', models.TextField()),
                ('identity_file', models.FileField(upload_to='identity_files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user_registration')),
            ],
            options={
                'db_table': 'user_verification',
            },
        ),
    ]
