# Generated by Django 5.0.6 on 2024-07-10 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0022_alter_user_verification_identity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_verification',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
