# Generated by Django 5.0.6 on 2024-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0023_user_verification_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_verification',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
