# Generated by Django 5.0.6 on 2024-07-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0025_withdrawal_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
