# Generated by Django 5.0.6 on 2024-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0026_contact_us_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_items',
            name='downloaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchased_items',
            name='max_download',
            field=models.IntegerField(default=10),
        ),
    ]
