# Generated by Django 5.0.6 on 2024-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0027_purchased_items_downloaded_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_items',
            name='discounted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
