# Generated by Django 5.0.6 on 2024-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0028_purchased_items_discounted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_items',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
