# Generated by Django 5.0.6 on 2024-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_dashboard', '0030_withdrawal_request_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_request',
            name='to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
