# Generated by Django 5.0.6 on 2024-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
